# pull official base image
FROM node:latest AS builder

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY ./frontend/package.json ./
COPY ./frontend/package-lock.json ./
COPY ./frontend/ /app/

RUN npm install
# build code in intermediate image
RUN npm run build  

FROM nginx:latest

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/
RUN mkdir -p /app/build
COPY --from=builder /app/build/ /app/build/
CMD nginx -g "daemon off; error_log /dev/stdout info;"
