FROM node:latest
WORKDIR /web

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY ./backend/package.json ./
COPY ./backend/package-lock.json ./
RUN npm install

# add app
COPY . ./

# start app
CMD ["npm", "start"]   
